export const RATE_LIMIT_METADATA_KEY = 'neara:rate-limit';

export type RateLimitBucket =
  | 'PUBLIC_SEARCH'
  | 'PUBLIC_SLOT_LOOKUP'
  | 'PUBLIC_BOOKING_CREATE'
  | 'PUBLIC_BOOKING_LOOKUP'
  | 'ADMIN_LOGIN'
  | 'PASSWORD_RESET';

export const RATE_LIMIT_ENV: Record<RateLimitBucket, string> = {
  PUBLIC_SEARCH: 'RATE_LIMIT_PUBLIC_SEARCH_PER_MINUTE',
  PUBLIC_SLOT_LOOKUP: 'RATE_LIMIT_PUBLIC_SLOT_LOOKUP_PER_MINUTE',
  PUBLIC_BOOKING_CREATE: 'RATE_LIMIT_PUBLIC_BOOKING_CREATE_PER_MINUTE',
  PUBLIC_BOOKING_LOOKUP: 'RATE_LIMIT_PUBLIC_BOOKING_LOOKUP_PER_MINUTE',
  ADMIN_LOGIN: 'RATE_LIMIT_ADMIN_LOGIN_PER_WINDOW',
  PASSWORD_RESET: 'RATE_LIMIT_PASSWORD_RESET_PER_HOUR',
};
