export const RATE_LIMIT_METADATA_KEY = 'neara:rate-limit';

export type RateLimitBucket =
  | 'PUBLIC_SEARCH'
  | 'PUBLIC_SLOT_LOOKUP'
  | 'PUBLIC_BOOKING_CREATE'
  | 'PUBLIC_BOOKING_LOOKUP'
  | 'ADMIN_LOGIN'
  | 'PASSWORD_RESET'
  | 'CUSTOMER_REGISTER'
  | 'CUSTOMER_LOGIN'
  | 'CUSTOMER_OTP_REQUEST'
  | 'CUSTOMER_OTP_CONFIRM';

export const RATE_LIMIT_ENV: Record<RateLimitBucket, string> = {
  PUBLIC_SEARCH: 'RATE_LIMIT_PUBLIC_SEARCH_PER_MINUTE',
  PUBLIC_SLOT_LOOKUP: 'RATE_LIMIT_PUBLIC_SLOT_LOOKUP_PER_MINUTE',
  PUBLIC_BOOKING_CREATE: 'RATE_LIMIT_PUBLIC_BOOKING_CREATE_PER_MINUTE',
  PUBLIC_BOOKING_LOOKUP: 'RATE_LIMIT_PUBLIC_BOOKING_LOOKUP_PER_MINUTE',
  ADMIN_LOGIN: 'RATE_LIMIT_ADMIN_LOGIN_PER_WINDOW',
  PASSWORD_RESET: 'RATE_LIMIT_PASSWORD_RESET_PER_HOUR',
  CUSTOMER_REGISTER: 'RATE_LIMIT_CUSTOMER_REGISTER_PER_MINUTE',
  CUSTOMER_LOGIN: 'RATE_LIMIT_CUSTOMER_LOGIN_PER_MINUTE',
  CUSTOMER_OTP_REQUEST: 'RATE_LIMIT_CUSTOMER_OTP_REQUEST_PER_HOUR',
  CUSTOMER_OTP_CONFIRM: 'RATE_LIMIT_CUSTOMER_OTP_CONFIRM_PER_MINUTE',
};
